### ISSUE TITLE
 Any reason not to use openjdk-7-jre-headless ?

### ISSUE THREAD

**Issue by webframp** [GoatOS/go_cd#3]
Seems like this could just pull in a bunch of unneeded deps: https://github.com/GoatOS/go_cd/blob/master/recipes/default.rb#L1

have you tried headless and it didn't work?

**Comment by rmoriz** [comment]
How about using the `java` community cookbook? Would allow a flexible selection of JRE

**Comment by ranjib** [comment]
@rmoriz @webframp sorry folks. i have somehow missed to notice this issue. @webframp i agree java installation should be pluggable. gocd official website provide debs which in-turm depends on openjdk. this cookbook was initially written to use those debs. later i wanted to control the use creation process so that agents can run unprivileged lxc containers, hence i tool the raw jar approach. i'll be making the jvm_home injection pluggable first. @rmoriz i wont use the community java thing, last time i checked it was using ark resource that does not support why run. also i think i was not able to run it on Pi as well.
sorry again for getting back so late :-/

**Comment by ranjib** [comment]
@rmoriz @webframp I am revisiting this, do you folks still want this? If so, do let me know, else i'll close this ticket.

**Comment by ranjib** [comment]
closed via https://github.com/GoatOS/go_cd/pulls
